### America has six times as many firearm homicides as Canada, and nearly 16 times as many as Germany

In [181]:
from __future__ import print_function
import sys
import time
from ConfigParser import ConfigParser
import pandas as pd

In [188]:
df = pd.read_excel("World firearms murders and ownership_SurveyData_2nd.xlsx")

In [189]:
df.head()

,Country/Territory,ISO code,Source,% of homicides by firearm,Number of homicides by firearm,"Homicide by firearm rate per 100,000 pop",Rank by rate of ownership,Average firearms per 100 people,Average total all civilian firearms
0,Albania,AL,CTS,65.9,56.0,1.76,70.0,8.6,270000.0
1,Algeria,DZ,CTS,4.8,20.0,0.06,78.0,7.6,1900000.0
2,Angola,AO,NaN,NaN,NaN,NaN,34.0,17.3,2800000.0
3,Anguilla,AI,WHO-MDB,24.0,1.0,7.14,NaN,NaN,NaN
4,Argentina,AR,Ministry of Justice,52.0,1198.0,3.02,62.0,10.2,3950000.0

In [175]:
df.describe()

,% of homicides by firearm,Number of homicides by firearm,"Homicide by firearm rate per 100,000 pop",Rank by rate of ownership,Average firearms per 100 people,Average total all civilian firearms
count,116.000000,116.000000,116.000000,176.000000,176.000000,1.760000e+02
mean,32.229310,1100.060345,4.885862,88.909091,10.236932,3.659139e+06
std,27.558191,3912.260441,10.752043,51.325991,12.082117,2.098244e+07
min,0.000000,0.000000,0.000000,1.000000,0.100000,1.800000e+03
25%,7.475000,7.000000,0.175000,44.750000,1.500000,1.175000e+05
50%,27.900000,33.000000,0.480000,88.000000,6.200000,4.000000e+05
75%,53.400000,282.750000,2.852500,133.000000,14.625000,1.250000e+06
max,100.000000,34678.000000,68.430000,178.000000,88.800000,2.700000e+08

In [190]:
df.shape

(185, 9)

In [191]:
df.dropna()[:5]

,Country/Territory,ISO code,Source,% of homicides by firearm,Number of homicides by firearm,"Homicide by firearm rate per 100,000 pop",Rank by rate of ownership,Average firearms per 100 people,Average total all civilian firearms
0,Albania,AL,CTS,65.9,56.0,1.76,70.0,8.6,270000.0
1,Algeria,DZ,CTS,4.8,20.0,0.06,78.0,7.6,1900000.0
4,Argentina,AR,Ministry of Justice,52.0,1198.0,3.02,62.0,10.2,3950000.0
5,Armenia,AM,CTS,13.0,9.0,0.29,52.0,12.5,380000.0
6,Australia,AU,NSO,11.5,30.0,0.14,42.0,15.0,3050000.0

In [194]:
df.drop(labels = ['ISO code','Source','% of homicides by firearm','Number of homicides by firearm','Rank by rate of ownership','Average firearms per 100 people','Average total all civilian firearms'], inplace=True,axis=1)

In [195]:
df['Homicide'] = df['Homicide by firearm rate per 100,000 pop']*10

In [196]:
df.head()

  Country/Territory  Homicide by firearm rate per 100,000 pop  Homicide
0           Albania                                      1.76      17.6
1           Algeria                                      0.06       0.6
2            Angola                                       NaN       NaN
3          Anguilla                                      7.14      71.4
4         Argentina                                      3.02      30.2

In [197]:
dfsort = df.sort_values(by = 'Homicide', ascending = False)

In [203]:
dfsort.dropna()[::10]

    Country/Territory  Homicide by firearm rate per 100,000 pop  Homicide
72           Honduras                                     68.43     684.3
22             Brazil                                     18.10     181.0
3            Anguilla                                      7.14      71.4
177           Uruguay                                      2.80      28.0
102         Macedonia                                      1.21      12.1
101        Luxembourg                                      0.62       6.2
147            Serbia                                      0.46       4.6
126  Northern Ireland                                      0.28       2.8
165        Tajikistan                                      0.22       2.2
8          Azerbaijan                                      0.12       1.2
1             Algeria                                      0.06       0.6
10            Bahrain                                      0.00       0.0

In [204]:
dfsort.loc[~(dfsort==0).all(axis=1)].head()

    Country/Territory  Homicide by firearm rate per 100,000 pop  Homicide
72           Honduras                                     68.43     684.3
51        El Salvador                                     39.90     399.0
83            Jamaica                                     39.40     394.0
179         Venezuela                                     38.97     389.7
67          Guatemala                                     34.81     348.1

In [200]:
df8 = dfsort[(dfsort['Country/Territory'] == 'Austria') | (dfsort['Country/Territory'] == 'Denmark') | (dfsort['Country/Territory'] == 'Netherlands') |
      (dfsort['Country/Territory'] == 'Sweden') |(dfsort['Country/Territory'] == 'Finalnd') |(dfsort['Country/Territory'] == 'Ireland') |
     (dfsort['Country/Territory'] == 'Canada')|(dfsort['Country/Territory'] == 'Australia')| (dfsort['Country/Territory'] == 'New Zealand')|
        (dfsort['Country/Territory'] == 'Germany')|(dfsort['Country/Territory'] == 'Luxembourg')| (dfsort['Country/Territory'] == 'Belgium')|
     (dfsort['Country/Territory'] == 'Swizerland')|(dfsort['Country/Territory'] == 'United States') ]

In [201]:
df8.to_csv('redesign1_homicideByCountry.csv', encoding='utf-8')